#!/bin/sh
if [ $# -ne 1 ]
then
	echo "Usage: ./gen-modpack [file]"
	exit
fi

FILE=$(cat $1 | tr " " "\n" | grep ":")
OUTPUT=""
for line in $FILE
do
	id1=$(echo $line | awk -F":" '{print($1)}')
	id2=$(echo $line | awk -F":" '{print($2)}')
	
	OUTPUT="$OUTPUT,{\"projectID\": \"$id1\", \"fileID\": \"$id2\", \"required\": true}"
done
echo "{\"files\": [$OUTPUT]}" | sed "0,/,/{s/,//}" | python -m json.tool | sed "0,/{/{s/{//}"

