#!/bin/sh

if [ $# -ne 2 ]
then
	echo "Usage: mon [on/off] [interface]"
	exit
fi

ip link set dev $2 down
if [ "$1" = "on" ]
then
	iw $2 set monitor none
else
	iw $2 set type managed	
fi
macchanger -r $2
ip link set dev $2 up
